G = pgv.AGraph(directed=True)
    G.add_node(1, label="odor?")
    G.add_node(2, label="ANISE")
    G.add_node(3, label="PUNGENT")
    G.add_node(4, label="SPICY")
    G.add_node(5, label="CREOSOTE")
    G.add_node(6, label="ALMOND")
    G.add_node(7, label="FISHY")
    G.add_node(8, label="MUSTY")
    G.add_node(9, label="FOUL")
    G.add_edge(1,2, label = "EDIBLE")
    G.add_edge(1,3, label="POISONOUS")
    G.add_edge(1,4, label="POISONOUS")
    G.add_edge(1,5, label="POISONOUS")
    G.add_edge(1,6, label="EDIBLE")
    G.add_edge(1,7, label="POISONOUS")
    G.add_edge(1,8, label="POISONOUS")
    G.add_edge(1,9, label="POISONOUS")
    G.add_node(10, label="NONE")
    G.add_edge(1, 10)
    G.add_node(11, label="spore-print-color?")
    G.add_edge(10,11)
    G.add_node(12, label="BROWN")
    G.add_node(13, label="BLACK")
    G.add_node(14, label="CHOCOLATE")
    G.add_node(15, label="GREEN")
    G.add_node(16, label="BUFF")
    G.add_node(17, label="YELLOW")
    G.add_node(18, label="ORANGE")
    G.add_edge(11,12, label="EDIBLE")
    G.add_edge(11,13, label="EDIBLE")
    G.add_edge(11,14, label="EDIBLE")
    G.add_edge(11,15, label="POISONOUS")
    G.add_edge(11,16, label="EDIBLE")
    G.add_edge(11,17, label="EDIBLE")
    G.add_edge(11,18, label="EDIBLE")
    G.add_node(19, label="WHITE")
    G.add_edge(11, 19)
    G.add_node(20, label="habitat?")
    G.add_edge(19, 20)
    G.add_node(21, label="LEAVES")
    G.add_node(22, label="PATHS")
    G.add_node(23, label="GRASSES")
    G.add_node(24, label="WASTE")
    G.add_node(25, label="WOODS")
    G.add_edge(20, 21)
    G.add_edge(20, 22, label="EDIBLE")
    G.add_edge(20, 23, label="EDIBLE")
    G.add_edge(20, 24, label="EDIBLE")
    G.add_edge(20, 25)
    G.add_node(26, label="gill-size?")
    G.add_edge(25, 26)
    G.add_node(27, label="BROAD")
    G.add_node(28, label="NARROW")
    G.add_edge(26, 27, label="EDIBLE")
    G.add_edge(26, 28, label="POISONOUS")
    G.add_node(29, label="cap-color?")
    G.add_edge(21, 29)
    G.add_node(30, label="BROWN")
    G.add_node(31, label="WHITE")
    G.add_node(32, label="CINNAMON")
    G.add_node(33, label="YELLOW")
    G.add_edge(29, 30, label="EDIBLE")
    G.add_edge(29, 31, label="POISONOUS")
    G.add_edge(29, 32, label="EDIBLE")
    G.add_edge(29, 33, label="POISONOUS")
    G.layout(prog="dot")
    G.draw("mushroom-decisiontree.png")