import sys
s = sys.argv[1]

print(s[2])
print(s[4])
print(len(s))
print(s[0])
print(s[-1])
print(s[-2])
print(s[3:8])
print(s[-5:])
print(s[2:])
print(s[::2])
print(s[1::3])
print(s[::-1])
print(s.index(" "))
print(s[:-1])
print(s[1:])
print(s.lower())
print(s.split())
print(len(s.split()))
print([c for c in s])
print(''.join(sorted(s)))
print(s[:s.index(" ")])
print(s==s[::-1])